[theme]
base = "light"
primaryColor = "#B43A32"
backgroundColor = "#F4F7F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#19211E"
font = "sans-serif"

[server]
headless = true
maxUploadSize = 15

[browser]
gatherUsageStats = false
